[package]
name = "crispycraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
building-blocks = "0.7"
wgpu = "0.12"
winit = "0.26"